'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class StockControlEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=StockControlEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property TDocTCrDT() As DbSet(Of TDocTCrDT)
    Public Overridable Property TDocTCrHD() As DbSet(Of TDocTCrHD)
    Public Overridable Property TDocTPiDT() As DbSet(Of TDocTPiDT)
    Public Overridable Property TDocTPiHD() As DbSet(Of TDocTPiHD)
    Public Overridable Property TDocTTrDT() As DbSet(Of TDocTTrDT)
    Public Overridable Property TDocTTrHD() As DbSet(Of TDocTTrHD)
    Public Overridable Property TMnyMUserMenu() As DbSet(Of TMnyMUserMenu)
    Public Overridable Property TMstMBomDT() As DbSet(Of TMstMBomDT)
    Public Overridable Property TMstMBomHD() As DbSet(Of TMstMBomHD)
    Public Overridable Property TMstMMaterial() As DbSet(Of TMstMMaterial)
    Public Overridable Property TMstMMenu() As DbSet(Of TMstMMenu)
    Public Overridable Property TMstMUser() As DbSet(Of TMstMUser)
    Public Overridable Property TMstMWarehouse() As DbSet(Of TMstMWarehouse)

End Class
