'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TDocTCrHD
    Public Property XVCxhDocNo As String
    Public Property XDCxhDocDate As Nullable(Of Date)
    Public Property XVCxhDocStatus As String
    Public Property XVCxhUsrCodeSave As String
    Public Property XVCxhUsrCodeApprove As String
    Public Property XVWahCode As String
    Public Property XVMatCode As String
    Public Property XVTxhRmk As String

End Class
