'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TDocTTrHD
    Public Property XVTxhDocNo As String
    Public Property XDTxhDocDate As Nullable(Of Date)
    Public Property XVTxhDocStatus As String
    Public Property XVTxhUsrCodeSave As String
    Public Property XVTxhUsrCodeApprove As String
    Public Property XVTxhWahCodeFrom As String
    Public Property XVTxhWahCodeTo As String
    Public Property XVTxhRmk As String

End Class
