'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TDocTPiHD
    Public Property XVPxhDocNo As String
    Public Property XDPxhDocDate As Nullable(Of Date)
    Public Property XVPxhDocStatus As String
    Public Property XVPxhUsrCodeSave As String
    Public Property XVPxhUsrCodeApprove As String
    Public Property XVPxhFrom As String
    Public Property XVPxhRmk As String

End Class
