'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TMnyMUserMenu
    Public Property XVUsrCode As String
    Public Property XVMnuCode As String
    Public Property XBUmnIsRead As Nullable(Of Boolean)
    Public Property XBUmnIsSave As Nullable(Of Boolean)
    Public Property XBUmnIsDelete As Nullable(Of Boolean)
    Public Property XBUmnIsCancel As Nullable(Of Boolean)
    Public Property XBUmnIsApprove As Nullable(Of Boolean)

End Class
